apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-tracker-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "64357ea7-2f5f-4afa-915d-314f95862d4e"
  labels:
    azure.workload.identity/use: "true"
